#Python Settings
 
[[language]]
name = "python"
auto-format = true
roots = ["uv.lock", ".git", "pyproject.toml"]
file-types = ["py", "ipynb"]
formatter = { command = "bash", args = ["-c", "uvx ruff check --fix - | uvx ruff format -"] }
language-servers = ["pyright", "ruff-lsp"]

[language-server.pyright]
command = "basedpyright-langserver"
args = ["--stdio"]
config = {}

[language-server.ruff-lsp]
command = "bash"
args = ["-c", "uvx ruff server"]
config = {}


# Zig Settings

[[language]]
name = "zig"
auto-format = true


# Godot GDScript Settings
[[language]]
name = "gdscript"
language-servers = ["godot"]


[language-server.godot]
command = "nc"
args = [ "127.0.0.1", "6005"]
